### ISSUE TITLE
Support for Eclipse 4.4. Luna

### ISSUE THREAD

**Issue by mbits** [wocommunity/wolips#107]
The error below occurs when using Eclipse 4.3 update site with Eclipse 4.4 Luna.

http://jenkins.wocommunity.org/job/WOLips43/lastSuccessfulBuild/artifact/temp/dist/ 

An error occurred while installing the items
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Install, operand=null --> [R]org.objectstyle.wolips.woproject.ant 4.3.20130721.3, action=).
Failed to prepare partial IU: [R]org.objectstyle.wolips.woproject.ant 4.3.20130721.3.

**Comment by rachelhan1024** [comment]
Hi there,

I know this issue has been closed, but there are some comments that I want to put into this issue as reference for else.

I forked and built wolips on my local and I think maybe I find the cause of the NPE...

Firstly, to replicate the NPE in eclipse 4.4:
1. open any html file
2. resize and shrink the WOD edit field to wherever the scroll bar of the WOD edit field is hidden
3. open another html file, then you will see the NPE

To fix the problem, I commented the following lines in file: org.objectstyle.wolips.componenteditor.part.HtmlWodTab.java
line 204 to 206 in method "hideWodIfNecessary" (Please see the following NPE stacktrace I got from eclipse LOG)
// if (!isHtmlActive()) {
// _templateContainer.forceFocus();
// }

And then I build wolips again, haven't seen the NPE again until now. Resizing the WOD edit field is not causing any NPE now.

I just committed some changes to https://github.com/rachelhan1024/wolips.git branch npeFixes4_4, hopefully it will just build smoothly. This branch is based on the branch "Wolfy42-eclipse_4_4" in wocommunity/wolips. Because in the commits, I was actually removing those Japanese comments, since it caused issue when I was doing the build. I am not sure if those changes can be merged back to the master or Wolfy42-eclipse_4_4. So, I just leave it there, so if anyone want to copy, it should work. hopefully...

Here is the LOG that I get for NPE exception:
java.lang.NullPointerException
at org.objectstyle.wolips.componenteditor.part.ComponentEditorPart.getEditor(ComponentEditorPart.java:403)
.........
at org.objectstyle.wolips.componenteditor.part.HtmlWodTab.hideWodIfNecessary(HtmlWodTab.java:205)
at org.objectstyle.wolips.componenteditor.part.HtmlWodTab.createTab(HtmlWodTab.java:152)
at org.objectstyle.wolips.componenteditor.part.ComponentEditorPart.createPages(ComponentEditorPart.java:201)
at org.objectstyle.wolips.componenteditor.part.ComponentEditor.createPages(ComponentEditor.java:171)
