### ISSUE TITLE
InPlace RuleEditor stores assignment class in the wrong place

### ISSUE THREAD

**Issue by NochEinKamel** [wocommunity/wolips#132]
We had a fun little 2 hour excursion into rulesets today because one of our team members is using the inplace RuleEditor in eclipse (on linux, no standalone available) and added two rules using BooleanAssignments.

Apparently, if you edit this Class-field
![image](https://cloud.githubusercontent.com/assets/379567/24255170/009a71de-0fe5-11e7-879f-20b078c0cc2c.png)

the resulting .d2wmodel file is written like this which is not correct.
![image](https://cloud.githubusercontent.com/assets/379567/24255198/12ba0118-0fe5-11e7-95ee-4582f0a83dc8.png)

The outer class always needs to be com.webobjects.directtoweb.Rule and the ...BooleanAssignment should only be written into the rhs part of the plist.

The inplace editor will still open the file but WO won't load the ruleset and the standalone editor crashes on load.

I think the error is in the [RuleEditor.java](https://github.com/wocommunity/wolips/blob/903fbe7d17f7849603e4baf568190a9444c837b9/wolips/core/plugins/org.objectstyle.wolips.ruleeditor/java/org/objectstyle/wolips/ruleeditor/editor/RuleEditor.java)  file:
```
wrong:

void setClassName(final String classname) {
	rule.setAssignmentClassName(classname);

	updateRules();
}


correct:

void setClassName(final String classname) {
	RightHandSide rhs = rule.getRightHandSide();
	rhs.setAssignmentClassName(classname);

	updateRules();
}

```

But I can't test/fix it :-/

**Comment by nullterminated** [comment]
I'm pretty sure the in place rule editor never actually worked. I believe I've got it fixed up enough to actually use now without butchering your rule files. Changes include fixing this bug (thanks for reporting), making rules save on a single line for easy git diffing, writing rules to a d2wmodel.txt file as well as rule model file, support for key comparison qualifiers on the LHS, custom selectors with the "key selector: value" format, sorting saved rules by priority, and fixing the priority sorting in the UI.

It still lacks support for rule model groups, there's no checkbox for disabling rules (disabled rules display a RuleIsDisabled = 'YES' in the LHS qualifier), there's still no file association for d2wmodel files, and there's not a nice combo box on the editor like there is on the cocoa version.

But it seems like it should now be usable at least.  There's some minor formatting differences on LHS qualifiers, where something like

smartRelationship.isToMany = '1'

becomes

smartRelationship.isToMany = 1

but these look harmless. Since the thing never really worked in the first place, I went ahead and pushed my changes. Hopefully this makes it a little nicer for everyone.
