### ISSUE TITLE
WOLips EntityModeler does not play nice with Eclipse Themeing

### ISSUE THREAD

**Issue by rucotec** [wocommunity/wolips#149]
All display colors in WOLips EntityModeler seem to be hardcoded. When using Eclipse Dark Theme or Darkes Dark Theme some things in EntityModeler become more or less invisible. E.g. the null/not null symbols in the columnar display of the entity attributes are almost invisible. Also the state of pressed/unpressed buttons in the attribute property panes are indistinguishable.
EntityModeler and all other places in WOLips shouldwork with light and dark themes.
![example2](https://user-images.githubusercontent.com/4901242/100243870-a4874500-2f36-11eb-8462-879e41a1add2.png)
![example1](https://user-images.githubusercontent.com/4901242/100243891-a9e48f80-2f36-11eb-82b2-2a906c610c4b.png)

**Comment by sgaertner** [comment]
See PR:
- Added white outlines to dark icons. Almost unchanged in Light Theme but now clearly visible in Dark Theme.
- Changed color used to indicate prototyped attributes from red to cyan. Better visible in Dark theme and looks less like an error / warning.
- Use checkboxes instead of toggles. For toggles the current state is hardly visible in Dark theme. Furthermore checkboxes are in general more verbose.

<img width="820" alt="dark" src="https://user-images.githubusercontent.com/1118920/141680449-538da8a0-a4e2-461d-937e-cb7d77d53ca9.png">
<img width="845" alt="light" src="https://user-images.githubusercontent.com/1118920/141680456-b903e761-63ee-4d4a-a14f-d53c97233099.png">
